SET SERVEROUTPUT ON

-- VPD function
CREATE OR REPLACE FUNCTION vpd_tenant_policy(
  p_schema IN VARCHAR2, p_table IN VARCHAR2
) RETURN VARCHAR2 AS
  v_tenant_id VARCHAR2(100);
BEGIN
  v_tenant_id := SYS_CONTEXT('bilera_ctx', 'tenant_id');
  IF v_tenant_id IS NULL THEN RETURN NULL; END IF;
  RETURN 'tenant_id = ' || v_tenant_id;
END;
/

-- Add policies one by one
BEGIN DBMS_RLS.ADD_POLICY(USER,'GROUPS','GROUPS_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'GROUPS','GROUPS_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'GROUPS','GROUPS_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'GROUPS','GROUPS_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

BEGIN DBMS_RLS.ADD_POLICY(USER,'ACTIVITIES','ACT_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ACTIVITIES','ACT_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ACTIVITIES','ACT_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ACTIVITIES','ACT_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

BEGIN DBMS_RLS.ADD_POLICY(USER,'TAGS','TAGS_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'TAGS','TAGS_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'TAGS','TAGS_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'TAGS','TAGS_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

BEGIN DBMS_RLS.ADD_POLICY(USER,'DOCUMENTS','DOCS_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'DOCUMENTS','DOCS_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'DOCUMENTS','DOCS_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'DOCUMENTS','DOCS_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

BEGIN DBMS_RLS.ADD_POLICY(USER,'ALBUMS','ALB_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ALBUMS','ALB_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ALBUMS','ALB_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'ALBUMS','ALB_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

BEGIN DBMS_RLS.ADD_POLICY(USER,'MEMBERSHIPS','MEMB_SEL_VPD',USER,'VPD_TENANT_POLICY','SELECT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'MEMBERSHIPS','MEMB_INS_VPD',USER,'VPD_TENANT_POLICY','INSERT'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'MEMBERSHIPS','MEMB_UPD_VPD',USER,'VPD_TENANT_POLICY','UPDATE'); END;
/
BEGIN DBMS_RLS.ADD_POLICY(USER,'MEMBERSHIPS','MEMB_DEL_VPD',USER,'VPD_TENANT_POLICY','DELETE'); END;
/

COLUMN object_name FORMAT A20
COLUMN policy_name FORMAT A20
SELECT object_name, policy_name FROM user_policies ORDER BY 1,2;

EXIT;
