/// <reference lib="webworker" />
import { precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

const SHARE_CACHE = "share-target-files";

// Intercept share target POST requests
self.addEventListener("fetch", (event: FetchEvent) => {
  const url = new URL(event.request.url);

  if (
    url.pathname === "/compartir" &&
    event.request.method === "POST"
  ) {
    event.respondWith(handleShareTarget(event.request));
  }
});

async function handleShareTarget(request: Request): Promise<Response> {
  try {
    const formData = await request.formData();
    const files = formData.getAll("files") as File[];
    const title = formData.get("title") as string | null;
    const text = formData.get("text") as string | null;

    const cache = await caches.open(SHARE_CACHE);

    // Store metadata
    const metadata = {
      title: title || "",
      text: text || "",
      fileCount: files.length,
      timestamp: Date.now(),
    };
    await cache.put(
      new Request("/_share/metadata"),
      new Response(JSON.stringify(metadata))
    );

    // Store each file in cache
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const arrayBuffer = await file.arrayBuffer();
      const response = new Response(arrayBuffer, {
        headers: {
          "Content-Type": file.type,
          "X-File-Name": encodeURIComponent(file.name),
          "X-File-Size": String(file.size),
        },
      });
      await cache.put(new Request(`/_share/file/${i}`), response);
    }
  } catch {
    // If parsing fails, still redirect to the page
  }

  // Redirect to the share page (GET)
  return Response.redirect("/compartir", 303);
}
